spring.application.name=server_member
spring.jpa.open-in-view=false

server.port=8814
#database
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3307/androidDB?useSSL=false&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

logging.level.org.springframework=info
logging.level.org.zerock=debug
logging.level.org.springframework.security=debug
